### ISSUE TITLE
Safe networks switch alpha => Error: 0: expected value at line 1 column 1 

### ISSUE THREAD

**Issue by Aleksey-Solin** [maidsafe/safe_network#1019]
Help me, please:

![2022-02-16_19-27-54](https://user-images.githubusercontent.com/77692334/154339056-19d7c093-a4e1-4325-a0ee-1b69eaf2119b.png)

**Comment by Aleksey-Solin** [comment]
I followed the following instructions, installed via quick launch:

https://github.com/maidsafe/safe_network/blob/main/sn_cli/README.md

**Comment by jacderida** [comment]
Hi @Aleksey-Solin 

Sorry, just to be clear, the networks in the user guide are just examples. They're not running networks you can connect to.

I will update the guide to clarify this.

Cheers,

Chris

**Comment by Aleksey-Solin** [comment]
> 

Thank you very much!

Please tell me which test network to enter to share the disk and to farm test coins.
