### ISSUE TITLE
Safe node killall => Error: 0: Failed to stop nodes (sn_node) processes: sn_node: no process found

### ISSUE THREAD

**Issue by Aleksey-Solin** [maidsafe/safe_network#1020]
Help me, please:
Safe node killall => Error: 0: Failed to stop nodes (sn_node) processes: sn_node: no process found

![image](https://user-images.githubusercontent.com/77692334/154491117-7c5bdcfa-6108-4ae9-9928-04ad3a483a4d.png)

**Comment by Aleksey-Solin** [comment]
> Это означает, что ни один процесс узла не был запущен, так что это не проблема. Вы что - нибудь начинали?
> 
> Если у вас возникли трудности, пожалуйста, сообщите, каким инструкциям вы следуете и какие шаги вы успешно выполнили.

Then I entered the following commands sequentially:, according to the instructions:

safe node install
safe node run-baby-fleming
safe networks
safe node killall
safe networks add alpha https://safe-testnet-tool.s3.eu-west-2.amazonaws.com/alpha-node_connection_info.config
safe networks
safe networks switch alpha

**Comment by happybeing** [comment]
I think those instructions are out of date and may have confused you.

Running baby fleming should work and set up a local network with several running nodes. You should then be able to try the CLI. However, you night not have a working system by following those instructions, though perhaps it did. If so you would not need the subsequent steps (adding and switching to a network).

The steps to add a network and switch to it should be used when joining a public test network, and will be different for different tests, and will only work once somebody else has set up a test network and provided instructions for joining.

So you can either:
- run a local baby fleming test and try out the CLI with it, or
- wait for a public test and follow the instructions given by the person who sets it up.

Recently the community has set up a public test each Friday afternoon/evening, so look out for the next one [here](https://safenetforum.org/c/community/comnet-testnets/80)

However, every few weeks MaidSafe will start their own test (lately called a 'playground') which you can test, so also look out for announcements about that in the forum.

Hope that helps.

**Comment by Aleksey-Solin** [comment]
> Я думаю, что эти инструкции устарели и, возможно, сбили вас с толку.
> 
> Запущенный бэби Флеминг должен работать и настроить локальную сеть с несколькими запущенными узлами. Затем вы должны быть в состоянии попробовать интерфейс командной строки. Однако, следуя этим инструкциям, вы не получите работающую систему, хотя, возможно, так оно и было. Если это так, вам не понадобятся последующие шаги (добавление и переключение в сеть).
> 
> Шаги по добавлению сети и переключению на нее следует использовать при присоединении к общедоступной тестовой сети, они будут разными для разных тестов и будут работать только после того, как кто-то другой настроит тестовую сеть и предоставит инструкции по присоединению.
> 
> Так что вы можете либо:
> 
> * запустите местный тест baby fleming и опробуйте с его помощью интерфейс командной строки, или
> * дождитесь публичного теста и следуйте инструкциям, данным человеком, который его проводит.
> 
> Недавно сообщество организовало публичный тест каждую пятницу днем/вечером, так что следите за следующим [тестом здесь](https://safenetforum.org/c/community/comnet-testnets/80)
> 
> Однако каждые несколько недель MaidSafe запускает свой собственный тест (в последнее время называемый "игровой площадкой"), который вы можете протестировать, поэтому также следите за объявлениями об этом на форуме.
> 
> Надеюсь, это поможет.

Thank you very much! :)
