### ISSUE TITLE
Simplify access error for registers.

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe_network#105]
```
/// Access denied for user
#[error("Access denied for user: {0:?}")]
AccessDenied(User),
```

QiMa commented:

> Actually something like : `AccessDenied(User, ErrorReason)`
shall cover both the current `AccessDenied` and `NoSuchUser`, with more explicity?

**Comment by grumbach** [comment]
`NoSuchUser` does not exist anymore, closing this now
