### ISSUE TITLE
on arm and termux on android 10 safe commands execute but dont return to prompt

### ISSUE THREAD

**Issue by dreamerchris** [maidsafe/safe_network#1054]
platform arm
using termux on android 10 on redmi 9AT (see image for specifics)
![Screenshot_2022-03-05-10-03-24-281_com android settings](https://user-images.githubusercontent.com/51272727/156874529-a3000697-9e8c-4628-bf5a-a357e6aae1e9.jpg)

using the safe commands leads to execution of the command without returning to cli prompt

it gets stuck and needs ctrl + c after every command!

well only safe -V runs ok as far as I know

tested with 0.50.4

safe networks as you see in next screenshot is stalling after execution and i have to press ctrl +c
![IMG_20220305_102235](https://user-images.githubusercontent.com/51272727/156875174-5eaf24cd-564f-4402-b34b-f18e9dbc89bc.jpg)

also safe node install just stalls and doesnt execute

**Comment by joshuef** [comment]
We don't actively test on android at the moment @dreamerchris, but there is an arm test suite. I'm curious if you've had any success on other arm platforms?
