### ISSUE TITLE
Nodes on podman container: "Unable to establish a connection"

### ISSUE THREAD

**Issue by Folaht** [maidsafe/safe_network#1059]
I start 16 IPv6 nodes on a podman container running Alpine Linux on an RPi4 running Manjaro Linux.
One by one they drop off until only the first one is left.

All errors are of this nature:

```
 ERROR 2022-03-09T14:44:08.302708Z [sn/src/node/core/bootstrap/join.rs:L164]:
	 ➤ join {network_genesis_key=PublicKey(0dae..b0d0) target_section_key=PublicKey(0dae..b0d0) recipients=[Peer { name: 6ba5e7(01101011).., addr: [2001:983:8610:1:575a:3c3a:a0a0:875b]:12000 }]}
	 ➤ Node cannot join the network since it is not externally reachable: [fdc2:2c37:1a5c:5ad1::1]:12001
 ERROR 2022-03-09T14:44:08.303123Z [sn/src/bin/sn_node.rs:L300]:
	 ➤ Unfortunately we are unable to establish a connection to your machine ([fdc2:2c37:1a5c:5ad1::1]:12001) either through a public IP address, or via IGD on your router. Please ensure that IGD is enabled on your router - if it is and you are still unable to add your node to the testnet, then skip adding a node for this testnet iteration. You can still use the testnet as a client, uploading and downloading content, etc. https://safenetforum.org/
```

It seems to work fine on IPv4, although I will add that the IPv4 is a couple of versions behind, so I don't know if this is a version issue or an IPv4/6 issue.  

What's the best action?

**Comment by b-zee** [comment]
Can you reproduce this outside of containers? I think more information is needed about your issue so that it can be reproduced. Only Ubuntu is officially supported by MaidSafe if I recall correctly, so I guess it would help them tremendously if you can reproduce it on there.

**Comment by Folaht** [comment]
I can't due to a different error. 

https://safenetforum.org/t/need-help-my-ipv6-test-network-tries-to-connect-to-127-0-0-1/36778

**Comment by Folaht** [comment]
"Can you reproduce this outside of containers?"

No. Outside of the containers it runs just fine.

**Comment by joshuef** [comment]
Sorry @Folaht , as @b-zee points out, we're only actively supporting ubuntu at this time. This sounds like an issue with the container setup as opposed to anything in `sn` if it's working fine outwith of the container.

I'm going to close this on that basis, though if you can an issue here on nomral ubuntu, feel free to comment back.

Thanks!
