### ISSUE TITLE
links against old mysterious crate resource_proof

### ISSUE THREAD

**Issue by jonassmedegaard** [maidsafe/safe_network#1148]
This project depends on the crate `resource_proof` which last saw a release almost a year ago, and points to https://github.com/maidsafe/resource_proof as its source repository - but that link is broken :-(

I wanted to report that that crate has a dependency on more than 3 years old `rand` v0.4.  Mentioning indirectly here instead... :-/

**Comment by joshuef** [comment]
Ah, the repo there has been archived over enthusiastically. We'll bring that back, it's not dead. Thanks for spotting @jonassmedegaard 🙇

**Comment by jacderida** [comment]
I've unarchived the repo and made it public again.

Can you raise the issue again on that crate please? I'll close this one.
