### ISSUE TITLE
Simplify SafeUrl. Add `from_safe_key` method eg

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#1231]
Building a SafeUrl instance sometimes requires first encoding to string and then decoding:

    SafeUrl::from_url(SafeUrl::encode_safekey(key))

Can we refactor this into:

    SafeUrl::from_safekey(key)

and to encode:

    SafeUrl::from_safekey(key).encode()

Goal: we have constructors for the different types of urls, removed all the `SafeUrl::encode_*()` methods and replaced it with the new API calls.

**Comment by jacderida** [comment]
Do we have an issue or issues for making the use of `SafeUrl` and strings in the API consistent? In some places we randomly use strings and in others it's the url type. This is both in internal code and public facing stuff, in either function arguments or return types. @bochaco once spoke of trying to use `AsRef` so you could use either strings or the url type, but when I looked into that, I wasn't sure it was going to be possible. I think this mechanism only works for simple, infallible types.
