### ISSUE TITLE
Client PUT Payment Flow

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#1434]
Inegration of client PUT payments requires:

(based off of: https://maidsafe.discourse.team/t/revamped-put-and-get-flows-with-dbc-payments/330)

## ClientSide
- Self-Encryption(SE) of _all_ chunks wanted to upload _before_  we attempt to pay/upload.
    - store SEd chunks in a (temp?) folder locally. (Is this client's local cache?)
 - When all chunks are encrypted, we `XorName(<all chunk data names/address>)` to get `PaymentXorName`, this is the section we must pay.
 - `PaymentSection` is a section in the network that the client will be paying for a batch of uploads/edits. With the PaymentXorName obtained from the step above, the client sends out a `CostInquiry` which fetches the cost of performing the network operation in that certain batch.
- Aggregate `GuaranteedQuoteShares`, store that locally for upload time.
- Choose DBCs to reissue (How? 💋 )
- Client reissues DBCs to payment recipients.
- Client prepares `RegisterPayment` encapsulating the output DBCs and the `GuaranteedQuote` which is to be sent to the `PaymentSection` for registering the payment and rewarding the nodes for the PUT.

### Note:

Self-encrypted data, should not all be sent in a oner (alone) as that _may_ reveal the data. 
PaymentXorName may will be needed using MerkleTree to derive it to hide DataAddress from section to prevent Self-Encryption being broken (https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Hash_Tree.svg/2880px-Hash_Tree.svg.png)

## Node Side
- Respond to a `CostInquiry` for a given batch of chunk `XorNames` with a `GuaranteedQuoteShare`
- How to calculate `PaymentQuote`?; KISS in initial impl, we can update this later...
- Validate `RegisterPayment` has been completed.
- ( Q: Do elders need to forward DBCs?? Is the reissue to PK not sufficient here?)
- Forward DBCs to adults as required.
- Respond to client with `PaymentReceiptShare`
- Store the `DebitableOp` and we can now look to upload chunks as/when we want!
- Upload chunks, with `DebitableOp` attached

- Verify DebitableOp before sending on storage requests to adults

## Questions

- What happens if a client doesn't get the `PaymentReceiptShare`?  The `RegisterPayment` Op is idempotent so should be replayable, right?
- Do elders need to forward DBCs to adults?? Is the reissue to PK not sufficient here?
- How/when do they forward DBCs
- Can we drop `Guaranteed` from `QuoteShare`, there are no non guaranteed quotes here...

## Definitions

PointerEdits her are what?? Registers??
```rust
/// Used when client asks PaymentSection for a quote.
enum CostInquiry {
    /// Chunk uploads
    Upload(BTreeSet<XorName>),
    /// Edits to the datatypes
    PointerEdit(BTreeSet<PointerEditKind>),
}
```

```rust
struct PaymentQuote {
    /// Provides context for the Quote
    inquiry: CostInquiry,
    /// A map of PublicKeys of nodes from the PaymentSection
    /// and the tokens the client has to pay them for storing/editing.
    payable: BTreeMap<PublicKey, Token>,
}
```

```rust 
struct GuaranteedQuoteShare {
    /// PaymentQuote for a batch of PUTs
    quote: PaymentQuote,
    /// SignatureShare of the PaymentQuote by an Elder
    sig: SignatureShare,
    /// PublicKey of the Section
    key: bls::PublicKey,
}
```

aggregated to: 

```rust
struct GuaranteedQuote {
    /// PaymentQuote for a batch of PUTs
    quote: PaymentQuote,
    /// Aggregated signature of the PaymentQuote from PaymentSection
    sig: bls::Signature,
    /// PublicKeySet of the Section
    key_set: bls::PublicKeySet,
}
```

```rust
/// A cmd sent to the `PaymentSection`.
/// The provided quote must be signed by a known section key.
/// The DBCs must be valid.
/// The provided payment must match the payees and amounts specified in the quote.
/// The set of chunk names (specified in the quote) are then guaranteed to be signed as paid for.
struct RegisterPayment {
    quote: GuaranteedQuote,
    payment: BTreeMap<PublicKey, sn_dbc::Dbc>,
}
```

```rust
struct PaymentReceiptShare {
    ops: CostInquiry,
    sig: SignatureShare,
    key: bls::PublicKey,
}
```

```rust
/// A given debitable op, is guaranteed to be accepted if 
/// the provided chunks/edits are present in the receipt.
enum DebitableOp {
    Upload {
        data: BTreeSet<Chunk>,
        payment: PaymentReceipt,
    },
    PointerEdit {
        ops: BTreeSet<PointerEdit>,
        payment: PaymentReceipt,
    },
}
```

**Comment by oetyng** [comment]
> PointerEdits her are what?? Registers??

Registers yes. To match today's code `RegisterWrite` could be used instead.
(This assumes that every edit to a register incurs cost.)

> Can we drop Guaranteed from QuoteShare, there are no non guaranteed quotes here...

`Guaranteed` can certainly be called something else. The idea is that the `PaymentQuote` is section signed, and therefore valid. And since there is no expiration, it's guaranteed to be valid.

A suggestion for first change would be to call it `SignedQuote`, or `SectionSignedQuote` which just informs on it being signed (and having section auth in the latter of the examples), but does not try to convey any context as to the validity duration properties.

...

If we want to restrict validity, then perhaps limit it to the prefix of the signing section. As long as the prefix is the same, the store cost is not going to be wildly different (so no reason the quote shouldn't be valid), and also gives ample of room for uploaders to act, minimizing UX impact of having the quote expiring under their nose as they're going about uploading stuff.

With such a limit, it'd not be necessary to convey more context on the validity duration properties I'd say. It'd just be one of those basic rules of the system.
