### ISSUE TITLE
Reenable ignored node tests

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#1758]
search for `#[ignore = "This needs to be refactored away from Cmd handling` and `#[ignore = "Needs to be refactored to take into` to see some disabled tests after we moved to bidi stream handling direct in the nodes.

These tests will likely need to be broken up, or tweaked to test the underlying code in a more unit test fashion, as we cannot rely on returned Cmd analysis here anymore. (Or we pass in a response stream.. but I think that's probably a whole lot of shimming things? 🤔 )

I'm not sure of the best way forwards here...

**Comment by oetyng** [comment]
My findings so far is that if we use a response stream to verify the acks, that entails spinning up instances of `MyNode` for all members in a mock section.

In effect, what we do then is an `E2E` test?

While this is possible to do, my question is if these are any longer **_node unit tests_** now?

**Q:** Shouldn't we move that to `E2E` test suite?

However, there is most likely still need for some more granular unit test around relevant components involved in that flow.

**Comment by oetyng** [comment]
With [PR#1796](https://github.com/maidsafe/safe_network/pull/1796), 4 out of 7 tests were re-implemented in `sn_client`.
As the remaining were deemed lower prio than the testnet tasks, I'm un-assigning from this task for now.
