### ISSUE TITLE
Add ability to easily use "happy path" elder messaging.

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#1759]
During a happy network, we should not require sending msgs to _all_ elders. We can significantly reduce messaging following this idea of only sending to _one_ elder. 

We now have ACKs once data has been stored at all 4 adults, so a first happy path here is tweaking flows to use one (closest?) elder only and expect only one ACK (after data is stored).

We should be able to;

- [ ]  set up CI to run HappyPathMode
- [ ] set up CI to run SecurePathMode
- [ ]  have a feature flag for selecting which
- [ ] verify data is at all 4 adults in both test sets
- [ ] Have a valid benchmark so we can test the difference
- - more?

**Comment by oetyng** [comment]
I'll take this one on now if that's OK?
I found that it is - if not a pre-requisite - so at least big helper when moving the spendbook tests from node units to sn_client e2e.

**Comment by joshuef** [comment]
Sounds good to me. 

I'd say let's stay defaulted to "strict mode" for now (aka, 7 elder acks). We can then add the extra feat flag test suite as an additional job.

Also, please take care to get this in as incrementally as you can. We can use this as a planning issue perhaps and have smaller ones for any intermediate steps if we need more clarification/discussion on the specifics?

**Comment by oetyng** [comment]
Will de-assign for now, as it wasn't helping with the tests as I first thought.
