### ISSUE TITLE
Remove `event_sender` in node

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#1778]
the event_sender struct is not used for anything beyond generating some logs, but adds a fair bit of code complexity.

We should remove this event sender as essentially unused.

Buttt... We still want to generate cmd logs. (Can this just be shifted to directly log inside the `process_cmd` func?

**Comment by RolandSherwin** [comment]
I looked at the code and seems like I need to modify some tests as well.. Will have a try..
