### ISSUE TITLE
Aarch64 ARM build

### ISSUE THREAD

**Issue by Folaht** [maidsafe/safe_network#182]
Is there any reason this architecture hasn't been included in the ARM support pull request?
This is very easy to do correct?
Copy-paste the armv7 merger and replace everything with aarch64 and it works?

I'm actually surprised the Armv7 has been added first.

**Comment by jacderida** [comment]
Apologies for the oversight.

I'll get this sorted very soon.

**Comment by Folaht** [comment]
No need to apologize.
I was busy doing this as well, but you did it way better than I did.
I only knew one had to edit the Makefile and main.yml.
