### ISSUE TITLE
The signed output of handover consensus should be what's used to update SectionsDag

### ISSUE THREAD

**Issue by davidrusu** [maidsafe/safe_network#1859]
Currently we run handover consensus to decide between concurrent DKG results. Handover consensus completes with `SectionSigned<SapCandidates>`

Instead of using that signature, we trigger a proposal flow to sign the SAP's that are inside the winning `SapCandidates`.

After those SAP(s) are signed, we then hand it over to network knowledge to update our section tree/dag.

We can remove a lot of complexity here if we were to simply use the `SectionSigned<SapCandidates>` coming out of handover consensus to update our sections DAG.

i.e. `SectionsDag::update(&mut self, new: SectionSigned<SapCandidates>)`.

**Comment by grumbach** [comment]
Currently Handover consensus completes with a `Decision<SapCandidate>`, which includes all the votes which are signed by the elders. From these votes it is indeed possible to verify that a given `SapCandidate` was agreed upon by the elders. Although it is probably less convenient and heavier both in verification time and size, it is equivalent to a `SectionSigned<SapCandidates>`.

We then indeed send out a `Proposal` in which the current elders sign the SAPs inside the `SapCandidates` and send them out to the candidates so they can aggregate it and obtain a `SectionSigned<SAP>` (signed by the old elders) which lets them update their network knowledge.

As you pointed out, this step adds an extra signature by the current elders that we could remove, but we can't remove the broadcast to inform the candidates. In other words we go from:

- consensus finishes: `Decision<SapCandidate>`
- elders broadcast signed `Proposal<SectionSigShare<SAP>>` to candidates
- candidates aggregate and get `SectionSigned<SAP>`

to:

- consensus finishes: `Decision<SapCandidate>`
- elders broadcast `Decision<SapCandidate>` to candidates

The pros:

- we save one signature from each elder per SAP (worse case 2 signatures per elder when splitting)
- we save signature accumulation and aggregation on the candidates side, as a result we don't need to keep a STATE for this step

The cons:

- we go from a light `SectionSigned<SAP>` proof of section succession to a very big `Decision<SapCandidate>`, this is a lot of data for us to keep for each section handover.
- `SectionSigned<SAP>` is 1 signature check, `Decision<SapCandidate>` is many signature checks from multiple elders as we need to check all the elder votes in it.

It feels to me the cons outweight the pros in this scenario, as we will need to store this `Decision` and verify it many times (proof chain etc).

If consensus had finished with `SectionSigned<SapCandidate>`, this change would have been perfect. Currently, changing consensus to end up with this output would be equivalent to moving the last sign/aggregate round to consensus!

I agree that the extra signature feels like a waste here though. But for now I think we don't have a good way to remove it without changing consensus more deeply. Or do you have an idea?
