### ISSUE TITLE
Investigate windows `get` file corruption

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#1902]
[as described here](https://safenetforum.org/t/offline-another-day-another-testnet/37788/67?u=joshuef)

**Comment by Stout77** [comment]
Note, encoding error happening with `safe cat` command.

Prerequisites to reproduce:

-windows 11 (problem might be in windows 10 as well, but not verified)
-running safe network, client installed on testing machine, client connected to correct network
- .jpg file uploaded to the safe network, safe:// address for the file 

How to reproduce:

-open PowerShell
-run `safe cat safe;//(address of the aformentioned .jpg file) >1.jpg`
-open command prompt (cmd.exe)
-run `safe cat safe;//(address of the aformentioned .jpg file) >2.jpg`

If reproduced, the files will have different encoding and size. 1.jpg will not be a valid jpg file
