### ISSUE TITLE
sn_cli setup completions (trivia tidying)

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_network#2000]
setup completions suggest a mixture of ```safe command help``` where perhaps none of those are intended and all should be hidden as ```safe command --help```

**Comment by willief** [comment]
Somewhat related, are there any occurrences where `safe command -h` does NOT work exactly as` safe command --help`?

**Comment by jacderida** [comment]
What exactly is being referred to here? Can you provide some examples please?

**Comment by willief** [comment]
I'm asking if `   -h `  **always** does the same as` --help`

I think @davidpbrown is pointing out that some commands have help without the preceding double dash. No I cant point at one right now, but Savid probably can :-)

**Comment by davidpbrown** [comment]
Yes, as Willie read it.. 
So, 
```
$ safe setup completions | grep '_describe -t commands' | sed "s/    _describe -t commands '//" | sed 's/commands.*//' | sort | grep  'help'
safe config add help 
safe config help 
safe config remove help 
safe files help 
safe help 
safe keys help 
safe networks help 
safe node help 
safe nrs help 
safe setup help 
safe wallet help 
safe xorurl help
```

**Comment by jacderida** [comment]
I would need to do a review to determine if any commands used `-h` as a short argument. The `--help` argument comes from StructOpt, the crate that generates the menus.

As for `setup completions`, I actually forgot that even existed. I'll review it again soon.
