### ISSUE TITLE
Make sure relocating nodes are using the AE flow when relocating

### ISSUE THREAD

**Issue by davidrusu** [maidsafe/safe_network#2006]
Once nodes are relocated, they should be following the same flow as a node joining a section. Part of that is using AE to update themselves to changes in the network.

Once this is in place, we can remove this check from the relocation logic as it should no longer be necessary check:
https://github.com/maidsafe/safe_network/pull/1982/files#diff-68aa390829114f95496b85caf2a42d625a335f797716c826e8261a1747110ee1R121-R124

**Comment by oetyng** [comment]
Solved by #2018.
