### ISSUE TITLE
Make relocation details verifiable.

### ISSUE THREAD

**Issue by davidrusu** [maidsafe/safe_network#2011]
Nodes are relocated between sections based on a `ChurnId`. These churn Id's decide two things:
1. which nodes will be relocated to a new section.
2. which section the node will be relocated to

So if they are forgeable, a faulty elder could arbitrarily force any node to relocate to a section of their choice. We need to ensure that this can't happen.

Currently the NodeState struct looks like this:

```
pub struct NodeState {
    peer: Peer,
    state: MembershipState,
    previous_name: Option<XorName>,
}

pub enum MembershipState {
    Joined,
    Left,
    Relocated(RelocationDst), // <-- what we are looking at in this issue
}

pub struct RelocationDst(XorName)
```

We need to replace the RelocationDst with something verifiable, like a RelocationTrigger that holds the verifiable event that triggered this relocation.

The end state would look something like this:

```
pub struct NodeState {
    peer: Peer,
    state: MembershipState,
    previous_name: Option<XorName>,
}

pub enum MembershipState {
    Joined,
    Left,
    Relocated(RelocationTrigger>),
}

pub struct RelocateTrigger(Decision<NodeState>)

impl RelocateTrigger {
    fn dst(&self) -> XorName; // derived from signed node state
}
```

**Comment by b00f** [comment]
Without going more into details, It looks to me that `NodeState` **has** a  `MembershipState` and `MembershipState` **has** a `NodeState`. This kind of  circular references (Foo has Bar and Bar has Foo ) might cause some difficulties in future. 
Don't you think we can assign some behavior to the  `NodeState` for `XorName` and `verification`? Also we can decouple the `Decision` from `RelocateTrigger`.
