### ISSUE TITLE
membership/network knowledge: Merge Section Peers and Membership

### ISSUE THREAD

**Issue by davidrusu** [maidsafe/safe_network#2081]
Currently we have 2 different view of section membership:
1. NetworkKnowledge::section_peers() - a set of section-signed nodestates 
2. Memberhip::section_members() - bootstrap members + a list of membership churn decisions

These two views can differ sometimes due to different rules for how these two membership sets are maintained.

Ideally we move to a single representation and I think that should be the the Membership view but moved to NetworkKnowledge.

That is, SectionPeers will become something like:

```rust
struct SectionPeers {
    bootstrap_members: BTreeSet<NodeState>,
    decisions: Vec<Decision<NodeState>>,
    archive: BTreeMap<XorName, Decision<NodeState>>,
}

impl SectionPeers {
    fn members(&self) -> BTreeSet<NodeState> {
        let mut members = self.bootstrap_members.clone()
        for decision in self.decisions.iter() {
            // ... apply decision to `members` set.
        }
    }
}
```
And Membership can then read the current section members state from NetworkKnowledge so we can drop the `Membership::{history, bootstrap_members}` field and just deal with driving the consensus flow.

Doing all this in one PR is probably too large a task so I think we can break it down into a few steps:

- [x] Change SectionPeers and AntiEntropy to deal with Decisions instead of SectionSigned, but keep everything else the same.
```rust
struct SectionPeers {
    members: BTreeMap<XorName, SectionSigned<NodeState>>,
    archive: BTreeMap<XorName, SectionSigned<NodeState>>,
}
// to
pub(super) struct SectionPeers {
    members: BTreeMap<XorName, Decision<NodeState>>,
    archive: BTreeMap<XorName, Decision<NodeState>>,
}

// and

AntiEntropyKind::Update { members: BTreeSet<SectionSigned<NodeState>> }
// to
AntiEntropyKind::Update { members: BTreeSet<Decision<NodeState>> }
```
- [x] Then we can make the change to SectionPeers to derive membership state from the bootstrap_members and decisions:
``` rust
struct SectionPeers {
    bootstrap_members: BTreeSet<NodeState>,
    decisions: Vec<Decision<NodeState>>,
    archive: BTreeMap<XorName, Decision<NodeState>>,
}
```
- [ ] Then finally delete the `Membership::{bootstrap_members, history}` fields and instead read that state from NetworkKnowledge.

I probably missed some steps along the way but I think that's the broad strokes.

**Comment by maqi** [comment]
One pain stuff for the switching is that Decision may hold multiple node_states , which cause much trouble to the currnet handling logic based on SectionSigned. 
In couple of places, I have to put some TODO points to highlight that currently we can only handle one node_state per each decision.

Also, Decision doesn't contain the info of the public section_key, which means have to iterate through all candidates to verify the sig to figure out who signed that NodeState. for example here: https://github.com/maidsafe/safe_network/blob/main/sn_interface/src/network_knowledge/section_peers.rs#L118 , when try to prune archived members based on certain steps of section_keys.

**Comment by davidrusu** [comment]
TODOs after #2089 
- [ ] remove `section_signed_to_decision()` helper
- [ ] validated Decision when we received it in `NetworkKnowledge::merge_members(...)`
- [ ] figure out how to deal with `SectionPeers::prune_members_archive()` since trying all recent section keys is not going to scale.
