### ISSUE TITLE
Moving age calculation into the interface (common) crate

### ISSUE THREAD

**Issue by b00f** [maidsafe/safe_network#2101]
We can move the logic behind calculating age from `XorName` to somewhere that all crates have access to it (like `sn_interface`)

```rust
pub fn calc_age(name: &XorName) -> u8 {
     name()[XOR_NAME_LEN - 1]
 } 
```

**Comment by joshuef** [comment]
is this code replicated over the whole code base? 

In general if you see a quick win for something like this you can fire up a PR with the change directly and we can look at it there / see any issues more clearly. 🙇

**Comment by RolandSherwin** [comment]
Fixed - https://github.com/maidsafe/safe_network/pull/2106
