### ISSUE TITLE
removing cargo-husky

### ISSUE THREAD

**Issue by b00f** [maidsafe/safe_network#2231]
I recommend that we remove the "[cargo-husky](https://github.com/maidsafe/safe_network/blob/42b2f9fb2e74bde45052a38b53835f27baedd175/sn_node/Cargo.toml#L121)" dependency from the project's dev-dependencies. 

The ".git" folder is part of the user's workspace and they may have their own preferences for managing Git hooks. For instance, some users may have custom hooks to check for spelling errors or perform other checks that are not covered by "cargo-husky". 

We can still enforce code formatting and run Clippy checks during the code review process without relying on "cargo-husky", and by doing so, we can allow users to have more control over their ".git" folder.

**Comment by joshuef** [comment]
I don't think using husky stops you? It just adds to what's already there, no?

**Comment by b00f** [comment]
> I don't think using husky stops you? It just adds to what's already there, no?

I used to remove it, before committing the code. Cargo-husky is kind of re-write the git hooks and that might not be a good choice.
