### ISSUE TITLE
Find how to detect when our closest nodes change

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#45]
We need to know when our closest bucket changes (how close? just data close? whole bucket?), such that we might then be able to trigger data replication to update new members and distances.

**Comment by joshuef** [comment]
GPT claims we just need something along these lines:

```rust

impl NetworkBehaviourEventProcess<()> for MyBehaviour {
    fn inject_event(&mut self, _: ()) {
        // Check for node failures and initiate the republishing process if necessary
        let mut closest_nodes = self.kademlia.closest_nodes(self.kademlia.key().clone()).into_iter();
        if let Some(node) = closest_nodes.find(|n| n.status().is_none()) {
            // Node failed, initiate the republishing process
            let key = node.key().preimage().to_owned();
            let value = self.kademlia.get_record(&key).map(|r| r.value).unwrap_or_default();
            let expiration = self.kademlia.get_record(&key).map(|r| r.expiration).unwrap_or_default();
            tokio::spawn(republish_value(self.kademlia.clone(), key, value, expiration));
        }
    }
}

```

--------------

edit:
That's wrong it seems, `NetworkBehaviourEventProcess` has been deprecated: https://docs.rs/libp2p/latest/libp2p/swarm/trait.NetworkBehaviour.html


EDIT:

I was framing this all wrong. Here we don't care if a node is gone or not, just that our closest peers changed!

**Comment by maqi** [comment]
As mentioned in the slack discussion, there are two points we can/shall carry out the closest check:
1, On newly NodeAdded 
2, On first removal of DeadNode

There is a snippet showing carry out targeted data replication on node churning, at 
https://github.com/maidsafe/safe_network/pull/155#issuecomment-1519964713
