### ISSUE TITLE
Trigger replication flows when close group changes

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#46]
We'll need to pull over the replication flows from the safe code (ie the random send of relevant data loop), and update nodes as/when our close nodes change (and so the holders change).

This could be on node join or leave

**Comment by maqi** [comment]
As discussed on the https://github.com/maidsafe/safe_network/pull/172 and https://github.com/maidsafe/safe_network/pull/155
For replication, we could:
1, Use targeted replication, as shown in the comment of PR 155
2, Use kad provider model, which:
   a, store data to kad as record directly
   b, make data holder as Provider, and store ProviderRecord to kad

It seems libp2p can carry out replication using built-in configs via the approach 2, which save lot of our work
And the PR https://github.com/maidsafe/safe_network/pull/179 implemented the approach 2.a .

The approach 2.b requires some extra work to query the data based on fetched ProviderRecord.
Which we might be needed with the grown of data size to be uploaded to the network.

**Comment by joshuef** [comment]
Closing this as using a `recordStore` sorts this
