### ISSUE TITLE
Discuss: Client Keytype. Do we just go BLS?

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#54]

**Comment by grumbach** [comment]
Currently libp2p `Keypair` type only supports:
- Ed25519 (default, and the one we use)
- Rsa
- Secp256k1
- Ecdsa

So even if we switch to bls we still need an ed key for that. 

On the other hand, nothing prevents us from adding bls as an option in libp2p and PR that up to the libp2p guys!

**Comment by joshuef** [comment]
Closing as not a massive priority at the moment.
