### ISSUE TITLE
[client] Most Futures returned are not Send

### ISSUE THREAD

**Issue by b-zee** [maidsafe/safe_network#62]
Cross post to https://github.com/maidsafe/sn_client/issues/1555.

A bit of a blocker for me at the moment, not sure if this is an unintended consequence.

**Comment by joshuef** [comment]
Definitely not intended. Not sure what'll have caused this. 

May be a good wee test to have for the APIs there too, to ensure we dont break this in the future. 👍

**Comment by b-zee** [comment]
I guess it's a good idea to add some test for this. I'm afraid this won't be the last time this can occur.

The cause was this piece of the commit https://github.com/maidsafe/self_encryption/commit/e76006387a24c88bb3acaacdc2484dcd1c6068f2#diff-a201b14c05de060075554dacd0000db6a080b1232185f0f5ddff68ea4ce19f62R578
The change seems innocent, but had a large effect due to the way Rust derives auto traits.

**Comment by joshuef** [comment]
Yeh, some integration test for this will be a great addition, here and encryption.

Good find @b-zee !
