### ISSUE TITLE
Add config option to error out of node on being voted off... / hard disconnecting

### ISSUE THREAD

**Issue by maqi** [maidsafe/safe_network#69]
Investigate whether the restart shall happen on routing only or on node level, when got disconnected to the section or got voted off by the section.

note: the current Event::Event::RestartRequired is no longer got fired from routing

ps: ideally bring back the perviously removed routing::drop::node_restart test back

**Comment by maqi** [comment]
we now consider make qp2p trying to re-connect on disconnection before firing a Disconnected event to upper layer.
as first introduced within the PR https://github.com/maidsafe/qp2p/pull/289

**Comment by joshuef** [comment]
qp2p retries connections for us now. 

We should have a config a config flag to automatically retry joining the network. (or to turn that off; keep auto restart as default).
