### ISSUE TITLE
[routing] require name change when promoted or demoted

### ISSUE THREAD

**Issue by maqi** [maidsafe/safe_network#71]
This is inherited from the issue https://github.com/maidsafe/sn_routing/issues/2112 :

When a node is about to be promoted to elder, it needs to generate a new name for itself so that the elder sets are always unique.

For example, currently we can have section progression like this:

```
A, B, C, D
A, B, C, E
A, B, C, D
```
So now 1 and 3 are identical which might make the section vulnerable to replay attacks (the demotion of D in step 2 could be replayed after step 3 to demote it again). There might be other, more subtle issues with this.

To prevent that, we should require that D changes its name before the promotion, so the progression would look like this (D' is the new name of D):

```
A, B, C, D
A, B, C, E
A, B, C, D'
```
The flow could look approximately like this:

The section decides to promote/demote some nodes (after a churn, ...)
The nodes that are not elders currently but that would become new elders are identified
A message is sent to these new to-be-elders (signed by the section and accumulated at the destination) to ask them to generate the new name
On receiving the message and verifying it, they generate the new name and send back a proof of that - a message containing the new name signed with the old key
When all proofs are received, the section proceeds with the promotion
To handle faulty nodes, we should give the to-be-elders a limited time to do the name change and if they fail to do so, we remove them from the promotion and replace with different nodes and repeat the process.

note: The name change request message could additionally include a name interval into which the new name must fall which can then be used to keep the section balanced - so when a split happens, roughly half of the elders go into one subsection and half into the other. If this could be made reliable it could allow us to remove some of the complexity which we currently have to handle the case where all the elders end up in only one subsection.

additional note: another way to handle this issue could be `force relocation during demotion` . That is when a node got demoted, it will be `relocated` to self section or a remote section.

**Comment by oetyng** [comment]
This seems like a quite desired feat still. Any updates?

> another way to handle this issue could be force relocation during demotion 

Seems like the simpler option to implement, no?
Perhaps even wrt performance.. or what do you think @maqi ?

**Comment by ineiti** [comment]
And why can't you include a timestamp or a counter in the set of elders? Then each set would be unique, and you wouldn't need a renaming of the nodes.

**Comment by joshuef** [comment]
@ineiti we try to avoid timestamps as that requires sync across all the relevant elders to decide what the actual "time" was.

**Comment by joshuef** [comment]
But it seems like we can close this as with recent membership it's not longer necessary 💪
