### ISSUE TITLE
look into optional ACKs. After elders have sent on to adults.

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_network#909]
We could use ACKs in a non-required fashion.

Worse case is we fall back onto current behaviour and optionally validate a PUT.

We can send an ACK back once a message has been processed at elders (ie, once the message has gone out to adults to store a chunk, OR once a register has been written).

The ack may then allow a client to stop querying/validating/waiting for AE flows to complete.

(Which in turn may simplify some tests)

**Comment by maqi** [comment]
Couple of points would like to be clarified:
1, Regarding the whole Put flow that could be `Client -> Client's Account Holder (to verify having enough allowance) -> DataHolders' Account Holder (to credit data_holders and check space) -> DataHolders`
Does the Ack only happens on step 1 (Client's Account Holder to Client), or on all steps?
If the Put flow has been changed, which step is expected to be Acked?

2, Does the Ack itself need to contain the whole content of the original message or just a msg_id of it?

3, The Ack itself still need to go through the AE, or it can be an excemption?

**Comment by joshuef** [comment]
I think point 1 is perhaps more 'all encompassing' than needs to be. 

I think there will be back and forth for paying for data. But the PUT of data + payment (what we have as just PUT) should hack an ACK from the receiving Elder, after they have processed the message.

2. Ack could just be for the `OperationId` (not the same as msg id. it's derived from the msg contents)
3. The Ack would not go through any AE as it would just be from Elder->Client.
