### ISSUE TITLE
sn_node: support logrotate style logfile rotation

### ISSUE THREAD

**Issue by happybeing** [maidsafe/safe_network#938]
The `sn_node` logfiles are currently closed after one hour, and a new file opened with a different name. The files grow quickly in size and each one can be 10MB or more.

Problem:
- a command such as `tail -f` or `vdash` stops following the logs on the first rotation
- logfiles take up too much space
 
Proposal: modify the behaviour to support `logrotate` style naming, compression and thresholds, specifically:
- the logfile being updated always has the same name
- rotated files are moved in sequence to new names with `.1`, `.2`, `.3` ... `.N` appended to the name of the first logfile
- rotated files are compressed (ideally optional)
- rotation is based on a default maximum size (ideally with configurable size or time)
- the number of logfiles kept is limited by default, say to ten (i.e. max N = 9), ideally configurable

This would keep the total size used more manageable and allow logfile watching programs to continue following the log as the logfiles are rotated. Ideally features will be configurable by CLI parameters on `sn_node` (and ultimately `safe node`).

This issue relates to the discussion on the forum [here](https://safenetforum.org/t/offline-comnet-friday-7-january-2022/36394/292?u=happybeing)

### Implementation Note
The current logging system uses the `tracing` module with the `tracing_appender` as here:

https://github.com/maidsafe/safe_network/blob/e9a9cc1096e025d88f19390ad6ba7398f71bc800/sn/src/bin/sn_node.rs#L100

I'm hopeful the new behaviour can be achieved by replacing the `RollingFileAppender` with a [RollingWriter](https://tracing.rs/tracing_appender/rolling/struct.rollingwriter) that provides a wrapper for a suitable module with `logrotate` functionality, such as [file_rotation](https://docs.rs/file-rotation/0.4.2/file_rotation/) (which implements `tokio::io::Write`) or [file_rotate](https://docs.rs/file-rotate/0.5.1/file_rotate/) (which implements `std::io::Write`).

**Comment by joshuef** [comment]
@happybeing that sounds most excellent. Very keen for this 👍

**Comment by happybeing** [comment]
I seem to have working code to address this using the `file_rotate` create, having used the `testnet` command to test it works with `tail --follow=name` and `vdash`.

Before I make a PR:
- would you like any of the configuration added to `sn_node` params? Current defaults are up to ten logfiles are kept, a max size of 36,000 lines per file and all but the most recent are compressed. See https://docs.rs/file-rotate/0.5.1/file_rotate/ for details of the configuration options.
- so far I've only modified one file, `sn_node.rs` by adding code to implement a struct `FileRotateAppender` which is then used instead of the `tracing_appender` from the `tracing` create. So I'm wondering if I should separate it into a new module, and if so where? It's not a lot of code, so should probably stay in `sn_node.rs` unless it could be reused eventually. I suppose I could even publish it as a separate crate so others can pull it in to modify the behaviour of `tracing`, but not in the short term.

**Comment by joshuef** [comment]
> would you like any of the configuration added to sn_node params
I think an easy option for number of files would be great yeh. W/ `0` being "just keep everything".

I'm not sure lines per file is necessary atm. (at least I don't imagine using it)

>It's not a lot of code, so should probably stay in sn_node.rs unless it could be reused eventually.

That sounds reasonable. I'm not sure of the scope or how elaborate the code is, but it's definitely something missing from tracing as far as I saw (when i wrote the current impl). So id imagine it could be usefu to other folk too.

But I'm happy for it to just live in `sn_node` for now if you are 👍

**Comment by happybeing** [comment]
Thanks for your help with the PR @joshuef - I'm very pleased to have contributed some code, even such a small fragment. Just to note, wrt to this (or a new issue) we will want to add CLI options to `safe node` to allow control of logfile output.

I suspect there are other CLI options to add/update so maybe that should be a separate issue for all `safe` CLI options.
